name: テスト（表示エラー）
description: テスト時の表示エラー起票
labels:
  - bug
title: 機能ID_エラー概要
body:
  - type: textarea
    attributes:
      label: エラー発生箇所
      description: エラーが発生しているページのURL
    validations:
      required: true

  - type: textarea
    attributes:
      label: ログイン情報
      description: テスト時に使用したユーザーIDとパスワード
    validations:
      required: true

  - type: dropdown
    attributes:
      label: 検証環境
      description: テスト時に使用した環境
      multiple: false
      options:
        - iPhone
        - Android
        - Firefox
        - Edge
    validations:
      required: true

  - type: dropdown
    attributes:
      label: 観点表との対応
      description: 観点表で満たせていないものを選択（複数選択可）
      multiple: true
      options:
        - 文字の見やすさ
        - 文字切れなし
        - 変な改行なし
        - リンク＆ボタン正常
        - テキスト入力正常
        - ラジオボタン正常選択
        - チェックボックス正常選択
        - プルダウン正常選択
        - その他（詳細を補足事項に記載）
    validations:
      required: true

  - type: textarea
    attributes:
      label: 補足事項
      description: 
    validations:
      required: false