name: スマホテスト（表示エラー）
description: テスト時の表示エラー起票
labels:
  - bug
body:
  - type: textarea
    attributes:
      label: エラー発生箇所
      description: エラーが発生しているページのURL
    validations:
      required: true
  - type: textarea
    attributes:
      label: ログイン情報
      description: テスト時に使用したユーザーIDとパスワード
    validations:
      required: true
  - type: dropdown
    attributes:
      label: スマホ機種
      description: テスト時に使用したスマートフォンの機種
      multiple: false
      options:
        - iPhone
        - Android
    validations:
      required: true
  - type: dropdown
    attributes:
      label: 観点表との対応
      description: 観点表で満たせていないものを選択
      multiple: true
      options:
        - a
        - b
        - c
        - その他（詳細を補足事項に記載してください）
  - type: textarea
    attributes:
      label: 補足事項
      description: 
    validations:
      required: false